spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.10.23:3306/oil?characterEncoding=utf-8&serverTimezone=GMT%2B8
eureka:
  client:
    service-url:
      defultZone: http://localhost:8761/eureka/
server:
  port: 8772
